[build]
functions = "./functions"
publish = "./public"

# Redirects to reknisioweb.cz
[[redirects]]
  from = "https://rsow.netlify.app"
  to = "https://reknisioweb.cz/"
  status = 301
  force = true

[[redirects]]
  from = "https://rsow.cz"
  to = "https://reknisioweb.cz/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.rsow.cz"
  to = "https://reknisioweb.cz/"
  status = 301
  force = true

# Redirect for short URLs
[[redirects]]
  from = "/solidni-webinar"
  to = "https://form.simpleshop.cz/oPwjx/buy/"
  status = 301

[[redirects]]
  from = "/75tipu"
  to = "https://www.reknisioweb.cz/p/kniha"
  status = 301

[[redirects]]
  from = "/:shortId"
  to = "/.netlify/functions/redirect/:shortId"
  status = 200

# Redirect /api/function-name to /api/v1/function-name
[[redirects]]
  from = "/api/:functionName"
  to = "/api/v1/:functionName"
  status = 200
  force = true

# Redirect /api/* to /.netlify/functions/*
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
